Robot Localization with Python and Particle Filters
===================================================

Import libraries and load map.

In [1]:
import numpy as np
import cv2
from cv2 import VideoWriter
from cv2 import VideoWriter_fourcc


map = cv2.imread("map.png", 0)
print(map)
HEIGHT, WIDTH = map.shape

video = VideoWriter(f'Robot_Localization.avi', VideoWriter_fourcc(*'MP42'), 15, (WIDTH, HEIGHT))


rx, ry, rtheta = (WIDTH/4, HEIGHT/4, 0)

[[ 79  80  82 ... 133 148 156]
 [ 78  79  81 ... 138 156 164]
 [ 76  77  79 ... 147 170 180]
 ...
 [181 181 182 ... 174 172 171]
 [178 178 178 ... 180 179 178]
 [177 177 177 ... 183 182 182]]


Map coordinate system

![title](images/coords.png)

CAUTION: The terrain height at X,Y coordinates is map(Y,X).

Read keyboard input.

In [2]:
STEP = 5
TURN=  np.radians(25)
def get_input():
    fwd = 0
    turn = 0
    halt = False
    k = cv2.waitKey(0)
    print(k)
    if k == 56:
        fwd = STEP
    elif k == 54:
        turn = TURN
    elif k == 52:
        turn = -TURN
    else:
        halt = True
    return fwd, turn, halt

Move the robot, with Gausssian noise.

![title](images/gaussian.png)

In [3]:
SIGMA_STEP = 0.5 #pixels
SIGMA_TURN = np.radians(5)

def move_robot(rx, ry, rtheta, fwd, turn):
    fwd_noisy = np.random.normal(fwd, SIGMA_STEP, 1)
    print("fwd_noisy = ", fwd_noisy)
    
    rx += fwd_noisy * np.cos(rtheta)
    ry += fwd_noisy * np.sin(rtheta)
    
    turn_noisy = np.random.normal(turn, SIGMA_TURN, 1)
    print("turn_noisy = ", np.degrees(turn_noisy))
    
    rtheta += turn_noisy

    return rx, ry, rtheta

Initialize particle cloud.

In [4]:
NUM_PARTICLES = 3000

def init():
    particles = np.random.rand(NUM_PARTICLES, 3) #3000 particles with three attributes rx, ry and rtheta
    particles *= np.array( (WIDTH, HEIGHT, np.radians(360)))
    return particles

Move the particles.

In [5]:
def move_particles(particles, fwd, turn):
    particles[:, 0] += fwd * np.cos(particles[:,2])
    particles[:, 1] += fwd * np.sin(particles[:,2])
    particles[:, 2] += turn
    
    particles[:,0] = np.clip(particles[:,0], 0.0, WIDTH-1)
    particles[:,1] = np.clip(particles[:,1], 0.0, HEIGHT-1)
    return particles

Get value from robot's sensor.

In [6]:
SIGMA_SENSOR = 2
def sense(x, y, noisy=False):
    x = int(x)
    y = int(y)
    if noisy:
        return np.random.normal(map[y, x], SIGMA_SENSOR, 1)
    return map[y, x]

Compute particle weights.

In [7]:
def compute_weights(particles, robot_sensor):    
    errors = np.zeros(NUM_PARTICLES)
    for i in range(NUM_PARTICLES):
        elevation = sense(particles[i, 0], particles[i, 1], noisy=False)
        errors[i] = abs(robot_sensor - elevation)
        
    weights = np.max(errors) - errors
    
    weights[
        (particles[:, 0] == 0) |
        (particles[:,0] == WIDTH-1) |
        (particles[:,1] == 0) |
        (particles[:,1] == HEIGHT-1)
    ] = 0.0
    
    weights = weights ** 3
    return weights

Resample the particles.

In [8]:
def resample(particles, weights):
    probabilities = weights/np.sum(weights)
    
    new_index = np.random.choice(
        NUM_PARTICLES,
        size = NUM_PARTICLES,
        p = probabilities)
    
    particles = particles[new_index, :]
     
    return particles

Add noise to the particles.

In [9]:
SIGMA_POS = 2
SIGMA_TURN = np.radians(10)

def add_noise(particles):
    noise  = np.concatenate(
        (
            np.random.normal(0, SIGMA_POS, (NUM_PARTICLES, 1)),
            np.random.normal(0, SIGMA_POS, (NUM_PARTICLES, 1)),
            np.random.normal(0, SIGMA_TURN, (NUM_PARTICLES, 1))
        ), 
        axis=1
    )
    particles += noise
    return particles

Display robot, particles and best guess.

In [10]:
def display(map, rx, ry, particles):
    lmap = cv2.cvtColor(map, cv2.COLOR_GRAY2BGR)
    
    # Display particles
    if len(particles) > 0:
        for i in range(NUM_PARTICLES):
            cv2.circle(lmap, 
                       (int(particles[i,0]), int(particles[i,1])), 
                       1, 
                       (255,0,0), 
                       1)
        
    # Display robot
    cv2.circle(lmap, (int(rx), int(ry)), 5, (0,255,0), 10)

    # Display best guess
    if len(particles) > 0:
        px = np.mean(particles[:,0])
        py = np.mean(particles[:,1])
        cv2.circle(lmap, (int(px), int(py)), 5, (0,0,255), 5)

    cv2.imshow('map', lmap)
    video.write(lmap)


Main routine.

In [11]:
particles = init()
while True:
    display(map, rx, ry, particles)
    fwd, turn, halt = get_input()
    if halt:
        break
    rx, ry, rtheta = move_robot(rx, ry, rtheta, fwd, turn)
    particles = move_particles(particles, fwd, turn)
    if fwd != 0:
        robot_sensor = sense(rx, ry, noisy=True)        
        weights = compute_weights(particles, robot_sensor)
        particles = resample(particles, weights)
        particles = add_noise(particles)
    cv2.destroyAllWindows()                        

cv2.destroyAllWindows()                        


56
fwd_noisy =  [4.50514807]
turn_noisy =  [12.18253979]
56
fwd_noisy =  [5.26174637]
turn_noisy =  [5.24015471]
54
fwd_noisy =  [0.23521969]
turn_noisy =  [27.26741964]
56
fwd_noisy =  [4.95196087]
turn_noisy =  [1.67650563]
56
fwd_noisy =  [6.08845985]
turn_noisy =  [-1.38110839]
54
fwd_noisy =  [0.00385989]
turn_noisy =  [31.22997312]
54
fwd_noisy =  [0.02313605]
turn_noisy =  [23.62618621]
54
fwd_noisy =  [-0.43485973]
turn_noisy =  [48.85248031]
56
fwd_noisy =  [5.74187523]
turn_noisy =  [24.78247906]
54
fwd_noisy =  [0.12729033]
turn_noisy =  [24.57846591]
56
fwd_noisy =  [5.03852895]
turn_noisy =  [-3.05844855]
54
fwd_noisy =  [-0.33263566]
turn_noisy =  [24.02394263]
56
fwd_noisy =  [5.66578731]
turn_noisy =  [4.40789778]
56
fwd_noisy =  [5.24095107]
turn_noisy =  [-5.71479022]
56
fwd_noisy =  [5.4012657]
turn_noisy =  [2.37025719]
56
fwd_noisy =  [5.2786067]
turn_noisy =  [10.47943807]
54
fwd_noisy =  [0.22212339]
turn_noisy =  [23.6459516]
56
fwd_noisy =  [5.69518875]
turn_no

52
fwd_noisy =  [0.69460517]
turn_noisy =  [-3.51765206]
56
fwd_noisy =  [4.02186661]
turn_noisy =  [2.55627554]
56
fwd_noisy =  [5.62289758]
turn_noisy =  [8.21064985]
52
fwd_noisy =  [-0.15928119]
turn_noisy =  [-17.80364528]
52
fwd_noisy =  [0.32204009]
turn_noisy =  [-30.02025937]
52
fwd_noisy =  [0.50562671]
turn_noisy =  [-28.07227931]
52
fwd_noisy =  [-0.27074339]
turn_noisy =  [-7.52706844]
56
fwd_noisy =  [5.35589901]
turn_noisy =  [11.0676711]
52
fwd_noisy =  [0.99465068]
turn_noisy =  [-32.65132643]
56
fwd_noisy =  [4.98183221]
turn_noisy =  [7.65109198]
52
fwd_noisy =  [0.0254078]
turn_noisy =  [-26.84323848]
52
fwd_noisy =  [-0.05607397]
turn_noisy =  [-9.64544543]
56
fwd_noisy =  [5.1355614]
turn_noisy =  [-6.7908529]
50


In [12]:
video.release()